### ISSUE TITLE
Not able to send the request

### ISSUE THREAD

**Issue by mhdazeem** [stephan1827/modbusTCP-Automation-Studio#3]
Hi,

I am trying to use the modbusTCP-Automation-Studio library to communicate with the Modbus Slave. Here is the scenario:

- I have a device that acts as a Modbus Slave and I want to communicate it from the Modbus Master which will be the Automation Studio. 
- For the HW configuration in the AS, I am using a Standard PC as I am waiting for my C30 to delivered soon. 
- I have all the configuration set as mentioned in the pdf file and I can see it is making connection with the Modbus Slave but not sending any request to get the data. I tried to debug and the error is in control statement (MBmaster.c):

```
if (((*(inst->p_cfg)).action_enable[inst->internal.last_req].single) || 
((inst->internal.send_timer[inst->internal.last_req] >= (*(inst->p_cfg)).action_param[inst->internal.last_req].timer) && ((*(inst->p_cfg)).action_enable[inst->internal.last_req].cyclic)))
```

[ModbusMaster.zip](https://github.com/br-automation-com/modbusTCP-Automation-Studio/files/5919548/ModbusMaster.zip)

![image](https://user-images.githubusercontent.com/5148166/106770031-7a888800-6635-11eb-9ae0-24c3e1345e85.png)

Any help will be really appreciated. Thanks
Azeem

**Comment by stephan1827** [comment]
I will try to help you with this issue but you should know that there is a modbus master included in Automation Studio now. Of course you can still use the library if you like. It would be great if you could share what Automation Studio Version you are using, the runtime version and the cycle time the master is running at. The code line you are referring to is sending the request when the timer for this request is expired or the request is configured as single shot. Make sure that the ModbusTcpMaster.cycle_time matches your task cycle time.

**Comment by mhdazeem** [comment]
Hi,

Thank you for your reply. I will look into the Built-in Modbus Studio. These are the details:

<?AutomationStudio Version=4.8.3.111 SP?>
ARsim = B4.82
```
MasterConfig.action_param[2].timer 	:= 500; 		(* Refresh timer for this item *)
ModbusTcpMaster.cycle_time 		:= 10; 		(* Master cycle time in ms *)

```

**Comment by stephan1827** [comment]
And the cycle time of the task in 10ms in Automation Studio? Please try the following settings for the ethernet configuration and make sure that the firewall is not blocking the communication.

![image](https://user-images.githubusercontent.com/2972703/106873912-419ff000-66d5-11eb-9c23-5dc667eb6cb4.png)

**Comment by mhdazeem** [comment]
Hi,

After setting the IP address to 0.0.0.0 just stopped working. 

I don't get this point _And the cycle time of the task is 10ms in Automation Studio?_. I am new to Automation Studio, can you please explain this to me? Thanks

**Comment by mhdazeem** [comment]
![image](https://user-images.githubusercontent.com/5148166/106877035-40b88f80-66d0-11eb-8913-7e384e2d892c.png)

**Comment by stephan1827** [comment]
When you run a simulation it is not reachable from outside your laptop because it runs on the loop back address 127.0.0.1. When you set the IP to 0.0.0.0 the simulation will use the physical network card instead. You should point your Automation Studio online configuration to that instead of 127.0.0.1. You can see in your picture that the task is running at 1000ms. You have to change that to 10ms or adjust the parameter ModbusTcpMaster.cycle_time to 1000.

**Comment by mhdazeem** [comment]
Hi,

When I set the IP Address to 127.0.0.1 I can see the AS maks the connection with the Slave address but giving the IP address to 0.0.0.0 doing nothing. I have also set the cyclictime to 1000 but still no luck.

**Comment by mhdazeem** [comment]
Hello,

It is working now. I have made a stupid mistake a stupid mistake. 

```
// I had all the array index set to 2.
MasterConfig.action_enable[0].cyclic 	    := 1; 			(* Read data cyclic *)
MasterConfig.action_param[0].p_pv	    := ADR(A_In); 	(* Store data in this variable *)
MasterConfig.action_param[0].quantity 	    := 125; 		(* Number of items to read *)
MasterConfig.action_param[0].unit 	    := 1;			(* Unit address - ignore if not specified *)
MasterConfig.action_param[0].start_addr   := 16#0; 		(* Read from this modbus address *)
MasterConfig.action_param[0].timer 	    := 500; 		(* Refresh timer for this item *)
MasterConfig.action_param[0].type 	    := 4; 			(* Function code for this item (4 := read inputs) *)
```

Thank you for your help.

**Comment by mhdazeem** [comment]
Hi,

I am going to close this issue. Well, this was not an issue it was me paying no attention. 

Thanks

**Comment by stephan1827** [comment]
Great to hear that it works

**Comment by mhdazeem** [comment]
Yes, now I am going to figure out how to have more than 1 slave in a sophisticated way.

Any Idea?

**Comment by stephan1827** [comment]
You can just make an array of the ModbusTcpMaster and MasterConfig variable and then make a loop in the cyclic part of your program. The config might be a little bit of copy and paste but if the slaves are all the same the only variable that changes is the PLC variable you read or write to.

**Comment by mhdazeem** [comment]
Great... Thanks for the help. It means in the Initialization part of the code I can only have the interface address.

**Comment by stephan1827** [comment]
The configuration should be in the init part too. Remember that you should not change the configuration on the fly because the library creates timer depending on your configuration. You have to make an array of MasterConfig and then use one index for each slave.

**Comment by mhdazeem** [comment]
ahh... Thanks.

Let me try to implement what you have explained now and then I will get back to you for more help.

Thanks. Really appreciated.

**Comment by mhdazeem** [comment]
Hi,

Good Morning + Afternoon. I hope you are fine. Well, I did get the loops for Master + Config but now I am running into an issue. It works fine for 1 device but for the second device it first gave me an Error 50202 then I increase the size of the buffers and now I am getting this error 50200. Here is the code:

```
PROGRAM _INIT
	
	brsstrcpy(ADR(interface), ADR('IF3'));					(* Ethernet interface used on this PLC *)
	
	(* --------------------------------------------------------------------
	Reset FUNCTION blocks AND data structure on startup (SGC)
	--------------------------------------------------------------------- *)
	brsmemset(ADR(ModbusTcpMaster), 0, SIZEOF(ModbusTcpMaster));
	brsmemset(ADR(MasterConfig), 0, SIZEOF(MasterConfig));
	brsmemset(ADR(logger), 0, SIZEOF(logger));
	
	FOR index := 0 TO TotalNumberOfIENodes - MINUS_LAST_INDEX BY 1 DO
		brsstrcpy(ADR(slave_ip[index]), ADR(ieNodes[index]));				(* Slave device IP address *)
	END_FOR;
	
	FOR index := 0 TO TotalNumberOfIENodes - MINUS_LAST_INDEX BY 1 DO
		MasterConfig[index].action_enable[0].cyclic		:= 1;
		MasterConfig[index].action_param[0].p_pv		:= ADR(ieNodeDB[index].A_In);
		MasterConfig[index].action_param[0].quantity 	:= 124;
		MasterConfig[index].action_param[0].unit 		:= 0;
		MasterConfig[index].action_param[0].start_addr	:= 16#0;
		MasterConfig[index].action_param[0].timer 		:= 100;
		MasterConfig[index].action_param[0].type 		:= 4;
	END_FOR;
	
	FOR index := 0 TO TotalNumberOfIENodes - MINUS_LAST_INDEX BY 1 DO
		ModbusTcpMaster[index].enable 					:= 1;
		ModbusTcpMaster[index].device					:= ADR(interface);
		ModbusTcpMaster[index].slave_ip_addr 			:= slave_ip[index];
		ModbusTcpMaster[index].p_cfg 					:= ADR(MasterConfig[index]);
		ModbusTcpMaster[index].cycle_time 				:= 100;
		ModbusTcpMaster[index].log.data_lines 			:= 20;
		ModbusTcpMaster[index].log.pData := ADR(logger[index]);
	END_FOR;
	
	StartStop := 1;
	
END_PROGRAM

PROGRAM _CYCLIC
	
	IF(StartStop) THEN
		FOR index := 0 TO TotalNumberOfIENodes - MINUS_LAST_INDEX BY 1 DO
			ModbusTcpMaster[index]();
		END_FOR;
	END_IF
	
	FOR index := 0 TO TotalNumberOfIENodes - MINUS_LAST_INDEX BY 1 DO
		IF(reset_error) THEN
			brsmemset(ADR(ModbusTcpMaster[index].last_error), 0, 2);
			reset_error := 0;
		END_IF
	END_FOR;
	
END_PROGRAM
```

![image](https://user-images.githubusercontent.com/5148166/107026615-e0465280-67a2-11eb-9564-f67cb96435f7.png)


I am only using two devices and the 2nd device work fine it is just the 1st slave. Any idea, please?

Thanks

**Comment by stephan1827** [comment]
You are pretty close, but you have a memory violation where you connect the logger variable. Define a new data type like this

![image](https://user-images.githubusercontent.com/2972703/107042188-bf412a00-67c1-11eb-9727-60fc532614dc.png)

Then change the logger variable to this

![image](https://user-images.githubusercontent.com/2972703/107042247-d4b65400-67c1-11eb-84cf-874eb3621423.png)

where 4 is the max number of your masters

**Comment by mhdazeem** [comment]
oh.... god.. It is working now... I did not pay attention to the logger settings. Thanks for pointing it out. Working like a charm. 

Really appreciate that.

**Comment by mhdazeem** [comment]
Hi,

I am sorry to keep bothering you again. I would appreciate your response. Is there a way in Automation Studio to Convert USINT to HEX? I want to do it in ST Language.

Thanks
Azeem
